import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';
import vm from 'node:vm';

const html = readFileSync(
  new URL('../../crates/server/src/api_client.html', import.meta.url),
  'utf8'
);
const script = html.match(/<script>([\s\S]*?)<\/script>/)?.[1];

if (!script) {
  throw new Error('api_client.html does not contain an inline script');
}

// The gateway contract the browser client speaks, generated by the Rust
// test `web_control_contract_fixture_is_current`. Driving the page against
// these real serialized DTOs — rather than hand-written stubs — means a
// wire change that regenerates the fixture and drops a field the page reads
// fails here, closing the loop the Rust gate opens.
const contract = JSON.parse(
  readFileSync(
    new URL('../../crates/server/src/api_client_contract.json', import.meta.url),
    'utf8'
  )
);

class Element {
  constructor(tag = '') {
    this.tag = tag;
    this.children = [];
    this.dataset = {};
    this.disabled = false;
    this.hidden = false;
    this.listeners = new Map();
    this.textContent = '';
    this.value = '';
    this.parent = null;
  }

  addEventListener(type, listener) {
    this.listeners.set(type, listener);
  }

  click() {
    this.listeners.get('click')?.();
  }

  append(...children) {
    for (const child of children) {
      child.parent = this;
      this.children.push(child);
    }
  }

  prepend(child) {
    child.parent = this;
    this.children.unshift(child);
  }

  replaceChildren(...children) {
    this.children = [];
    this.append(...children);
  }

  get lastElementChild() {
    return this.children.at(-1) ?? null;
  }

  remove() {
    if (!this.parent) return;
    this.parent.children = this.parent.children.filter((child) => child !== this);
    this.parent = null;
  }
}

const SELECTORS = [
  '#connect',
  '#token',
  '#connect-button',
  '#status',
  '#workspaces',
  '#workspace-empty',
  '#workspace-count',
  '#warnings',
  '#events',
  '#event-empty',
  '#event-count',
  '#control',
  '#control-workspace',
  '#spawn-agent',
  '#spawn-shell',
  '#instruction',
  '#inject',
  '#refresh-output',
  '#agent-output',
];

function loadClient({ eventStream = 'open' } = {}) {
  const elements = new Map(SELECTORS.map((selector) => [selector, new Element()]));
  const tokenInput = elements.get('#token');
  const tokenTag = html.match(/<input\b[^>]*\bid="token"[^>]*>/)?.[0] ?? '';
  tokenInput.required = /\brequired\b/.test(tokenTag);
  // The control panel ships hidden in the markup; mirror that so the shim
  // matches the browser's initial state.
  elements.get('#control').hidden = /<section\b[^>]*\bid="control"[^>]*\bhidden\b/.test(html);

  const requests = [];
  const fetch = async (path, options = {}) => {
    const body = options.body ? JSON.parse(options.body) : undefined;
    requests.push({
      path,
      method: options.method ?? 'GET',
      headers: { ...(options.headers ?? {}) },
      body,
    });
    if (path === '/v1/health') return json(contract.responses.health);
    if (path === '/v1/workspaces') return json(contract.responses.workspaces);
    if (path === '/v1/agents') return json(contract.responses.agents);
    if (path === '/v1/commands') return json(contract.responses.command);
    if (path === '/v1/agents/inject') return json(contract.responses.inject);
    if (path === '/v1/agents/output') return json(contract.responses.output);
    if (path === '/v1/events') {
      return {
        ok: true,
        status: 200,
        body: {
          getReader() {
            return {
              read:
                eventStream === 'eof'
                  ? async () => ({ done: true })
                  : () => new Promise(() => {}),
            };
          },
        },
      };
    }
    throw new Error(`unexpected request: ${path}`);
  };

  vm.runInNewContext(script, {
    AbortController,
    TextDecoder,
    Date,
    document: {
      createElement: (tag) => new Element(tag),
      querySelector: (selector) => elements.get(selector),
    },
    fetch,
  });

  return {
    elements,
    requests,
    submit() {
      if (tokenInput.required && tokenInput.value === '') return false;
      elements.get('#connect').listeners.get('submit')({ preventDefault() {} });
      return true;
    },
  };
}

function json(payload) {
  return {
    ok: true,
    status: 200,
    async json() {
      return payload;
    },
    async text() {
      return '';
    },
  };
}

async function settle() {
  for (let turn = 0; turn < 4; turn += 1) {
    await new Promise((resolve) => setImmediate(resolve));
  }
}

async function connected(options) {
  const client = loadClient(options);
  client.elements.get('#token').value = 'secret';
  assert.equal(client.submit(), true);
  await settle();
  return client;
}

test('connects without an authorization header when the gateway has no token', async () => {
  const client = loadClient();

  assert.equal(client.submit(), true);
  await settle();

  assert.deepEqual(
    client.requests.map(({ path }) => path),
    ['/v1/health', '/v1/workspaces', '/v1/agents', '/v1/events']
  );
  for (const request of client.requests) {
    assert.equal(request.headers.Authorization, undefined);
  }
});

test('the connect handshake carries the bearer token on every request', async () => {
  const client = await connected();

  assert.deepEqual(
    client.requests.map(({ path }) => path),
    ['/v1/health', '/v1/workspaces', '/v1/agents', '/v1/events']
  );
  for (const request of client.requests) {
    assert.equal(request.headers.Authorization, 'Bearer secret');
  }
});

test('renders the workspace inbox from the live contract shape', async () => {
  const client = await connected();

  const workspace = contract.responses.workspaces.workspaces[0];
  assert.ok(workspace.name, 'contract workspace still carries a name');
  assert.ok(workspace.key, 'contract workspace still carries a key');
  assert.ok('branch' in workspace, 'contract workspace still carries a branch');

  const [row] = client.elements.get('#workspaces').children;
  const [name, source, branch] = row.children;
  assert.equal(name.textContent, workspace.name);
  assert.equal(branch.textContent, `⎇ ${workspace.branch}`);
  const upstream = workspace.pr ?? workspace.gh_issues?.[0] ?? workspace.linear_issues?.[0];
  assert.equal(source.textContent, upstream?.repo ?? workspace.project_key ?? 'local');

  // The running-agent projection tags the row it belongs to.
  const agent = contract.responses.agents.agents[0];
  assert.ok(agent.workspace_key, 'contract agent still carries a workspace_key');
  assert.ok(agent.agent, 'contract agent still carries an agent id');
  assert.equal(agent.workspace_key, workspace.key, 'the agent joins on the workspace key');
  const badge = row.children.find((child) => child.className === 'agent-badge');
  assert.ok(badge, 'the running agent badges its workspace row');
  assert.ok(badge.textContent.includes(agent.agent));
});

test('selecting a workspace reveals the control surface', async () => {
  const client = await connected();
  const workspace = contract.responses.workspaces.workspaces[0];

  const control = client.elements.get('#control');
  assert.equal(control.hidden, true);

  client.elements.get('#workspaces').children[0].click();

  assert.equal(control.hidden, false);
  assert.equal(client.elements.get('#control-workspace').textContent, workspace.key);
});

test('spawning an agent posts a Spawn command bound to the selected workspace', async () => {
  const client = await connected();
  const workspace = contract.responses.workspaces.workspaces[0];
  client.elements.get('#workspaces').children[0].click();
  client.requests.length = 0;

  client.elements.get('#spawn-agent').click();
  await settle();

  const spawn = client.requests.find(({ path }) => path === '/v1/commands');
  assert.ok(spawn, 'the client posted to /v1/commands');
  assert.equal(spawn.method, 'POST');
  assert.equal(spawn.headers.Authorization, 'Bearer secret');
  assert.equal(spawn.headers['Content-Type'], 'application/json');
  assert.equal(spawn.body.type, 'Command');
  assert.equal(spawn.body.payload.Spawn.session_key, workspace.key);
  assert.deepEqual(spawn.body.payload.Spawn.kind, { Agent: 'claude' });

  // Every field the client sends must be a known Spawn field on the wire
  // the gate pins (the client omits the serde-defaulted fields).
  const pinned = contract.requests.spawn_agent.payload.Spawn;
  for (const key of Object.keys(spawn.body.payload.Spawn)) {
    assert.ok(key in pinned, `${key} is a pinned Spawn field`);
  }

  // A spawn refreshes the running-agent projection.
  assert.ok(client.requests.some(({ path }) => path === '/v1/agents'));
});

test('starting a shell posts a Shell-kind Spawn command', async () => {
  const client = await connected();
  client.elements.get('#workspaces').children[0].click();
  client.requests.length = 0;

  client.elements.get('#spawn-shell').click();
  await settle();

  const spawn = client.requests.find(({ path }) => path === '/v1/commands');
  assert.ok(spawn, 'the client posted to /v1/commands');
  assert.equal(spawn.body.payload.Spawn.kind, 'Shell');
});

test('sending an instruction injects it into the workspace agent', async () => {
  const client = await connected();
  const workspace = contract.responses.workspaces.workspaces[0];
  client.elements.get('#workspaces').children[0].click();
  client.requests.length = 0;

  const instruction = client.elements.get('#instruction');
  instruction.value = 'Take another pass at the failing test.';
  client.elements.get('#inject').click();
  await settle();

  const inject = client.requests.find(({ path }) => path === '/v1/agents/inject');
  assert.ok(inject, 'the client posted to /v1/agents/inject');
  assert.equal(inject.method, 'POST');
  assert.equal(inject.headers.Authorization, 'Bearer secret');
  assert.deepEqual(inject.body, {
    workspace: workspace.key,
    text: 'Take another pass at the failing test.',
    submit: true,
  });

  assert.ok(contract.responses.inject.accepted, 'contract inject reply still reports acceptance');
  assert.equal(instruction.value, '', 'the composer clears once the inject is accepted');
});

test('refreshing output reads the agent tail and renders it', async () => {
  const client = await connected();
  const workspace = contract.responses.workspaces.workspaces[0];
  client.elements.get('#workspaces').children[0].click();
  client.requests.length = 0;

  client.elements.get('#refresh-output').click();
  await settle();

  const output = client.requests.find(({ path }) => path === '/v1/agents/output');
  assert.ok(output, 'the client posted to /v1/agents/output');
  assert.deepEqual(output.body, { workspace: workspace.key, tail: 200 });

  assert.ok('output' in contract.responses.output, 'contract output reply still carries output text');
  assert.equal(client.elements.get('#agent-output').textContent, contract.responses.output.output);
});

test('every request the client makes stays within the declared /v1 contract', async () => {
  const client = await connected();
  client.elements.get('#workspaces').children[0].click();
  client.elements.get('#spawn-agent').click();
  client.elements.get('#spawn-shell').click();
  client.elements.get('#instruction').value = 'go';
  client.elements.get('#inject').click();
  client.elements.get('#refresh-output').click();
  await settle();

  const allowed = new Set(contract.endpoints);
  for (const { path } of client.requests) {
    assert.ok(allowed.has(path), `${path} is outside the declared web-control contract`);
  }
});

test('reports a clean event-stream EOF as disconnected', async () => {
  const client = await connected({ eventStream: 'eof' });

  assert.equal(
    client.elements.get('#status').textContent,
    'Live event stream disconnected. Reconnect to resume.'
  );
  assert.equal(client.elements.get('#status').dataset.tone, 'error');
});
